ParameterizedBuilds/parameterized-builds

- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHook.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHookTest.java
Use of proper User-Token when not using dedicated Token. see #9
> Sloppy fix for issue #9

- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHook.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/PullRequestHook.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/GetQueryStringParameters.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java
- src/main/resources/static/parameterized-build-hook.soy
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHookTest.java
also extended four Tests (mocking) and parameterized-build-hook.soy accordingly
> regarding issue #11, added $REPOSITORY and $PROJECT 

- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServlet.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java
squid:S1192 - String literals should not be duplicated.
This pull request removes 78 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1192
George Kankava
> squid:S1192 - String literals should not be duplicated

- src/main/java/com/kylenicholls/stash/parameterizedbuilds/conditions/BaseCondition.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/conditions/HookIsEnabledCondition.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/conditions/ManualButtonCondition.java
common-java:DuplicatedBlocks - Source files should not have any duplicated blocks.
This pull request removes 40 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/common-java:DuplicatedBlocks
George Kankava
> common-java:DuplicatedBlocks - Source files should not have any duplicated blocks

- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServlet.java
squid:S1989 - Exceptions should not be thrown from servlet methods.
This pull request removes 260 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1989
George Kankava
> squid:S1989 - Exceptions should not be thrown from servlet methods

- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java
This pull request is focused on resolving occurrence of Sonar rule
squid:S1854 - Dead stores should be removed.
This pull request removes technical debt of 30 minutes.
https://dev.eclipse.org/sonar/rules/show/squid:S1854
George Kankava
> squid:S1854 - Dead stores should be removed

- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHook.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1132 - Strings literals should be placed on the left side when checking for equality.
squid:S134 - Control flow statements "if", "for", "while", "switch" and "try" should not be nested too deeply.
squid:S1161 - "@Override" annotation should be used on any method overriding (since Java 5) or implementing (since Java 6) another one.
This pull request removes technical debt of 55 minutes.
https://dev.eclipse.org/sonar/rules/show/squid:S1132
https://dev.eclipse.org/sonar/rules/show/squid:S134
https://dev.eclipse.org/sonar/rules/show/squid:S1161
George Kankava
> Multiple code improvements - squid:S1132, squid:S134, squid:S1161

- src/main/resources/static/parameterized-build-hook.js
- src/main/resources/static/parameterized-build-hook.soy
This PR is not finished but I would like to get comments on this approach while I look into updating the parameterized-build-hook.soy file. 
This should make adding and modifying triggers and trigger-specific fields much more intuitive on the js side of things.
I also fixed some discrepancies in tabs vs spaces in this file which makes reading the diff rather difficult. Sorry about that.
> [WIP] Simplify trigger creation code

- README.md
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsService.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/BitbucketVariables.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResource.java
- src/main/resources/scripts/jenkins/feature/build-dialog.js
- src/main/resources/scripts/jenkins/pb-pr-trigger.js
- src/main/resources/static/parameterized-build-hook.js
- src/main/resources/static/parameterized-build-hook.soy
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/JenkinsTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsServiceTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/item/JobTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResourceTest.java
This PR introduces support for multibranch pipelines in jenkins. Multibranch pipelines are triggered a bit differently so they need additional support. This feature has been requested a few times in issues #93 and #63.
I've added some tests to ensure that the correct build URLs are generated for multibranch pipelines and normal jobs. I've also manually tested both. Because this feature has been developed over a significant period of time, I'd appreciate some double checking, at least for regular jenkins jobs.
> Support Multibranch Pipelines

- pom.xml
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/AccountServer.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServer.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServerFactory.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServlet.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/GlobalServer.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/ProjectServer.java
- src/main/resources/templates/jenkins-admin-settings.soy
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServletTest.java
This PR adds a button on the jenkins settings pages to test if a jenkins connection is configured correctly. This change updates both global admin and project jenkins settings pages. Feature was requesting in #100.
I also refactored some of the jenkins settings code to make it a bit easier to work with. Naming could probably be a bit better.
> Test Jenkins Button

- README.md
- pom.xml
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHook.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/ScopeProjectVisitor.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsService.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHookTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/PullRequestHookTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServletTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/conditions/BuildPermissionsConditionTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/conditions/ManualButtonConditionTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResourceTest.java
Best to be prepared. Everything seems to work as expected.
> Remove deprecated methods

- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java
Workaround a SSL connection problem described in #142 ; this is not really a fix of the sporadic, temporary connection issues, just a retry on failure. However, it worked on our site.
> issue-142 Add retries to connect to workaround SSL issues

- README.md
Remove duplicated word from README.MD #157
> Remove duplicated word

- src/main/resources/atlassian-plugin.xml
#154 
https://travis-ci.org/mishahliba/parameterized-builds/builds/437993782
Added missed client-condition to client-web-item. Checked locally. Screenshot attached
> Issue 154. Add manual build button for tags

- .github/ISSUE_TEMPLATE.md
- README.md
- pom.xml
Bump jar version. While at it, I also updated the readme about jenkins folders and fixed the headers in the issue template.
> Release 3.2.7

- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHook.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/PullRequestHook.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/AccountServer.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/GlobalServer.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/ProjectServer.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsService.java
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResource.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHookTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/item/JobTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResourceTest.java
With the upgrade to a new major version, I wanted to take a few minutes to go through and clean up some bits of sloppy code that has sneaked into this project over time.
> Suppress warnings, parameterize raw types, and remove unused variables

- parameterized-client/package-lock.json
- parameterized-client/src/jenkins_settings/state-reducers.js
This fixes #196. I also added a package-lock.json to satisfy #200.
> Render empty jenkins settings when undefined

- pom.xml
> Set maven-compiler-plugin version

- pom.xml
Forgot to update the version number in last PR
> Update version number

- README.md
- parameterized-client/src/hook/job.js
- src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/BitbucketVariables.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/item/BitbucketVariablesTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResourceTest.java
Adding the PREMAIL parameter as requested via #225
> Add PREMAIL build parameter

- pom.xml
The mockito stuff is a major(-ish) update. Should be helpful later down the road.
> Update test versions

- pom.xml
> Update server from 6.3.0 to 6.8.0

- docs/spec.yml
As suggested in https://github.com/ParameterizedBuilds/parameterized-builds/issues/105#issuecomment-549149280 I added spec for possible API to manage repository jobs.
Unfortunately, I have very little time to make more progress on this ticket, but I interested in making your package better :)
> WIP: #105 repository settings API

- parameterized-client/package-lock.json
- parameterized-client/package.json
Updating package-lock file due to detected security vulnerabilities by Github. Also updated axios version just because.
> Resolve JS security vulnerabilities

- parameterized-client/package.json
- pom.xml
> Bump versions to 4.0.10

- src/test/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHookTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServletTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/JenkinsTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/conditions/BuildPermissionsConditionTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/conditions/HookIsEnabledConditionTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/conditions/ManualButtonConditionTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRApprovedHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRAutoMergedHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRDeclinedHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRDeletedHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRDestRescopedHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRMergedHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PROpenedHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRReopenedHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRSourceRescopedHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRTestBase.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PushHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/RefCreatedHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/RefDeletedHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/RefHandlerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsServiceTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/item/BitbucketVariablesTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/item/JenkinsResponseTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/item/JobTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/item/ServerTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/item/UserTokenTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResourceTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/GlobalResourceTest.java
- src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/ProjectResourceTest.java
This looks worse than it is. Just a bunch of style fixes.
> Fix indentation and line lengths

- src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Server.java
> Use empty string default to avoid npe

- pom.xml
- src/main/resources/atlassian-plugin.xml
- src/main/resources/scripts/jenkins/pb-pr-trigger.js
PR for Bitbucket 7.0.0
Currently the only change is to the PR manual build button which now uses the new extensions API: https://community.developer.atlassian.com/t/announcement-bitbucket-server-7-0-early-access-program-eap-release/34814
> Bitbucket 7 updates

- parameterized-client/package-lock.json
- parameterized-client/package.json
Working through dependabot issues.
> Update js libraries

- pom.xml
> Update java security vulnerabilities
