ParameterizedBuilds/parameterized-builds

src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServlet.java

squid:S1948 - Fields in a "Serializable" class should either be transient or serializable.
This pull request removes 120 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1948
George Kankava

squid:S1948 - Fields in a "Serializable" class should either be transient or serializable

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsService.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResource.java

This pull request is focused on resolving occurrences of Sonar rules
squid:S1905 - Redundant casts should not be used.
squid:S1197 - Array designators "[]" should be on the type, not the variable.
squid:S2864 - "entrySet()" should be iterated when both the key and value are needed.
This pull request removes 20 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1905
https://dev.eclipse.org/sonar/rules/show/squid:S1197
https://dev.eclipse.org/sonar/rules/show/squid:S2864
George Kankava

Multiple code improvements - squid:S1905, squid:S1197, squid:S2864

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServlet.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/conditions/BaseCondition.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/conditions/HookIsEnabledCondition.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/conditions/ManualButtonCondition.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java

This pull request is focused on resolving occurrences of Sonar rules
squid:S1948 - Fields in a "Serializable" class should either be transient or serializable.
squid:RedundantThrowsDeclarationCheck - Throws declarations should not be superfluous.
squid:S1854 - Dead stores should be removed.
This pull request removes 60 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1948
https://dev.eclipse.org/sonar/rules/show/squid:RedundantThrowsDeclarationCheck
https://dev.eclipse.org/sonar/rules/show/squid:S1854
George Kankava

Multiple code improvements - squid:S1948, squid:RedundantThrowsDeclarationCheck, squid:S1854

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java

We installed the plugin and pointed it to our Jenkins instance, but it kept erroring out with
> c.k.s.p.ciserver.Jenkins Exception for parametized build: Length Required
Adding these couple lines fixed it.

Fixed 411 no length specified error

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsService.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java

This pull request is focused on resolving occurrence of Sonar rule
squid:S1166 - Exception handlers should preserve the original exception.
This pull request removes 50 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1166
George Kankava

squid:S1166 - Exception handlers should preserve the original exception

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServlet.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java

This pull request is focused on resolving occurrence of Sonar rule
squid:S1132 - Strings literals should be placed on the left side when checking for equality.
This pull request removes 30 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1132
George Kankava

squid:S1132 - Strings literals should be placed on the left side when checking for equality

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHook.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/PullRequestHook.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/conditions/BaseCondition.java

This pull request is focused on resolving occurrence of Sonar rule
squid:S1161 - "@Override" annotation should be used on any method overriding (since Java 5) or implementing (since Java 6) another one.
This pull request removes 35 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1161
George Kankava

squid:S1161 - "@Override" annotation should be used on any method overriding (since Java 5) or implementing (since Java 6) another one

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/conditions/BaseCondition.java

squid:S3038 - Abstract methods should not be redundant.
This pull request removes 2 minutes of technical debt.
George Kankava

squid:S3038 - Abstract methods should not be redundant

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsService.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsServiceTest.java

squid:S1168 - Empty arrays and collections should be returned instead of null.
This pull request removes 30 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1168
George Kankava

squid:S1168 - Empty arrays and collections should be returned instead of null

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java

squid:S1155 - Collection.isEmpty() should be used to test for emptiness.
This pull request removes 2 minutes of technical debt.
https://dev.eclipse.org/sonar/rules/show/squid:S1155
George Kankava

squid:S1155 - Collection.isEmpty() should be used to test for emptiness

---

pom.xml
src/main/java/com/kylenicholls/stash/parameterizedbuilds/PullRequestHook.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/PullRequestHookTest.java

Solves issue #56. However, I'm not convinced this is the best solution. I tried to look into something along the lines of [this](https://developer.atlassian.com/bitbucket/server/docs/latest/how-tos/responding-to-application-events.html) or [this](https://developer.atlassian.com/confdev/confluence-plugin-guide/writing-confluence-plugins/making-your-plugin-modules-state-aware). However, I was not able to make either of these work. Maybe someone else can manage it.

Created hook enabled check for pull requests

---

pom.xml
src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java

As mentioned in both [Issue-67](https://github.com/KyleLNicholls/parameterized-builds/issues/67) and [Issue-65](https://github.com/KyleLNicholls/parameterized-builds/issues/65), a Jenkins instance with CSRF protection can not be triggered. Instead, the request will return with a 403 status code. This branch solves the issue by always trying to retrieve a crumb from the Jenkins instance and adding the appropriate header if a crumb is returned.
This creates a side effect where a Jenkins instance without CSRF protection will be queried for the crumb which will return a 404. In this case, no crumb header is added to the original request. An alternative to this approach, a checkbox could be added to the jenkins settings to indicate if CSRF protection is set on the jenkins instances and only …

Added support for Jenkins CSRF protection

---

pom.xml
src/main/resources/scripts/jenkins/pb-pr-trigger.js

For ISSUE #54, choice params were fixed for the manual build in branch view pages. However, I did not include the fix in pb-pr-trigger.js so the manual button in the pull requests pages were still broken (as brought up by ISSUE #72). This PR adds the fix to pull requests page that was missing.

Add choice params fix to pr requests page

---

pom.xml
src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResource.java
src/main/resources/atlassian-plugin.xml
src/main/resources/scripts/jenkins/pb-pr-trigger.js
src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResourceTest.java

This took substantially longer than I thought it would...
Bitbucket 5 removes the deprecated bitbucket.pull-request.toolbar.actions for web.items for the bitbucket.pullrequest.action for client-web-items. However, the repository key is not available in the context passed to conditions in this section unlike our other client-web-items for the build dialogs. This means that the conditions we've defined will not work for this new client-web-item. Instead, client-conditions (condition functions defined in javascript) need to be specified to do the same logic as before. Since only one client-condition can be on a client-web-item (all but the first are ignored) I packaged them all into one javascript function in the script we were already loading into that item.
I'm fairly confident this should …

Bitbucket 5 compatibility

---

pom.xml
src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java
src/main/resources/atlassian-plugin.xml
src/main/resources/scripts/jenkins/pb-pr-conditions.js
src/main/resources/scripts/jenkins/pb-pr-trigger.js

Turns out the updates to the pb-pr-trigger.js script caused the button to not load the build dialog elements so it would do absolutely nothing. To fix this, I've reverted  pb-pr-trigger.js file to the previous version and moved the pr-conditions function to a file new, pb-pr-conditions.js. This allows the conditions to function independently from the trigger so no unintended side effects are present.
I don't know if we want to release this as a 3.0.1 release or if there's a way to replace the released version on bitbucket.
Later, I would like to fix up this section of code so that there isn't so much repetitive code between build-dialog, pb-pr-trigger, and pb-pr-conditions. However, for now its more important that the latest release works.

Fix 3.0.0 pr build button

---

README.md
pom.xml
src/main/java/com/kylenicholls/stash/parameterizedbuilds/conditions/BuildPermissionsCondition.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsService.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResource.java
src/main/resources/atlassian-plugin.xml
src/main/resources/less/hooks.less
src/main/resources/static/parameterized-build-hook.js
src/main/resources/static/parameterized-build-hook.soy
src/test/java/com/kylenicholls/stash/parameterizedbuilds/conditions/BuildPermissionsConditionTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsServiceTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResourceTest.java

As suggested by ISSUE #51, permissions can be set to restrict certain users from triggering build. This uses the Bitbucket repository permissions to determine if a user can use a trigger.
I've tested this rather extensively. There is a slight bug when downgrading from a version with this feature to a previous one without manual trigger permissions where a null job is created. Since this requires downgrading and the null job doesn't seem to have any real effect, I don't consider it worth addressing.

Created permissions check for manual trigger

---

src/main/resources/scripts/jenkins/pb-pr-conditions.js

To avoid TypeError on length-request on null-property, added prior check
if hook is enabled on repository after all. Also avoids 404 error if no
jobs are available for specified repository.

TypeError Fix for Pullrequest Condition Check

---

pom.xml
src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java

As mentioned in #71, When Build Token Root Plugin is enabled, two builds will be triggered instead of one. This is due to the naive way the base url was being parsed from the jenkins rest url that triggers the job when trying to get the crumb. This PR fixes this by using the URL lib to rebuild the base url instead.
I have manually tested this with both Build Token Root Plugin enabled and disabled and both CSRF protection enabled and disabled. All cases behave as expected.

Fix duplicate calls when Build Token Root Plugin used

---

README.md
pom.xml
src/main/java/com/kylenicholls/stash/parameterizedbuilds/PullRequestHook.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsService.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java
src/main/resources/less/hooks.less
src/main/resources/static/parameterized-build-hook.js
src/main/resources/static/parameterized-build-hook.soy
src/test/java/com/kylenicholls/stash/parameterizedbuilds/PullRequestHookTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsServiceTest.java

As requested by Issue #38 and #86, this PR adds the ability to restrict when Jenkins jobs are triggered via a PR Destination regex.
#86 also requested a filter for the source branch. While this would be simple enough, I don't like how the PR java logic is becoming somewhat spaghetti with this feature and would like to investigate cleaning it up before adding another conditional field.

Create Filter for PR Destination

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHook.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/PullRequestHook.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHookTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/PullRequestHookTest.java

ExecutorService.
Bitbucket, by default, will allocate one event processing thread per
CPU core. Bitbucket development recommends minimizing the activities
executed on the event threads.
See the following for more information:
https://github.com/Eernie/bitbucket-webhooks-plugin/issues/54

Move hook processing from event thread to dedicated thread pool via an

---

pom.xml
src/main/resources/static/parameterized-build-hook.soy

Apparently, I can't count.
The soy template uses the expected number of fields of all combined jobs to determine how many jobs to display. Each job has 9 fields but the soy was expecting 10. Luckily, soy rounds up so everything works as expected until a repo hits 10 jobs. This results in the json containing 90 fields so we expect 9 jobs to exist. The next time the soy is loaded, the last job is not loaded so saving the jobs again will actually delete the 10th job. #112  brings this issue to light.
This PR re-aligns the number of fields in a job with the expected number. If possible the json payload should probably be shifted towards a nested structure so this sort of bug doesn't happen again. It would also put us in a better spot for #105 since it would be much easier to add or remove …

ISSUE-113 jobs not displaying in repo settings

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHook.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/AccountServer.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServerFactory.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServlet.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Server.java
src/main/resources/templates/jenkins-admin-settings.soy
src/main/resources/templates/jenkins-user-settings.soy
src/test/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHookTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/PullRequestHookTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServletTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/JenkinsTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRAutoMergedHandlerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRDeclinedHandlerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRDeletedHandlerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRHandlerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRMergedHandlerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PROpenedHandlerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PushHandlerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/RefCreatedHandlerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/RefDeletedHandlerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/item/JobTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/item/ServerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResourceTest.java

We have jenkins listening on a sub-context, not on root path.
However the context was removed from the url when trying to fetch a csrf token.
logic has been separated and added to a jenkins server configuration
the CSRF is now configured by a checkbox per jenkins server
test have been updated accordingly

Fix issue with the CSRF jenkins crumb token

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRHandler.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/TestEventFactory.java

As issue #119 brought up, we don't trigger PR events when a forked repo created a PR. This is because we set the repo to be the source repo and not the target repo. Therefore, builds still trigger on the forked repo when the forked repo creates a PR but not the original. This doesn't seem to make a whole lot of sense since the target repo is the one that will be impacted by the PR, not the source. 
This change swaps which repo gets the trigger. I plan on adding a possible regression warning to this release if we decide to go this way.

Trigger PR events on target repo rather than source repo

---

pom.xml
src/main/resources/templates/jenkins-user-settings.soy

With the latest version adding a "Test Jenkins" button on the global and project level settings, a name attribute is required on the form submission buttons to determine what action to take (test or save). These names were added to the project and global jenkins settings soy templates but not the user-level jenkins settings. This is causing a loss of functionality for a significant number of users (see Issue #130). 
This PR adds the missing name attribute, thus fixing the issue. Considering the scope of this bug, I plan to release the new version once this PR is merged.

Add name attribute to user jenkins settings

---

src/main/resources/atlassian-plugin.xml

Apparently the Atlassian Marketplace changed the parameter for data center compatibility and so the plugin is no longer showing as data center compatible. This change should fix that.

Add new data center compatibility param

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRMergedHandler.java

In the PRMergedHandler we are attempting to get the new commit created by the merge for a bitbucket variable. However on remote merges bitbucket does not populate this value. This was causing a NullPointerException that could be seen in the logs. This PR adds null checking to the mergeCommit.
This should solve issue #166.

Make sure the merge commit is not null

---

src/main/resources/atlassian-plugin.xml

Due to new data center plugin requirements, I don't plan on supporting bitbucket data center anymore. The requirements can be found [here](https://developer.atlassian.com/platform/marketplace/dc-apps-submitting-your-app/).
I'm sad to see that we will no longer maintain data center compatibility but I feel I don't have the resources to do all the testing that is required.

Remove data center compatibility

---

.gitignore
parameterized-client/package.json
parameterized-client/src/hook/job.js
parameterized-client/src/hook/state-reducers.js
parameterized-client/src/hook/view.js
src/main/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHook.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServerFactory.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsService.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResource.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHookTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/PullRequestHookTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/CIServletTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/JenkinsTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRHandlerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PRTestBase.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResourceTest.java

This PR introduces a new option in the job definitions. Users can now choose to use either the global or project jenkins server to run their jobs on. Only servers that are defined will be available to choose from.
I'm not sure how useful this feature will be on it's own but it sets up a lot of the code we need to allow users to specify multiple jenkins servers per project.

Allow Jenkins Selection

---

pom.xml
src/main/resources/scripts/jenkins/feature/build-dialog.js
src/main/resources/scripts/jenkins/pb-blayout-trigger.js
src/main/resources/scripts/jenkins/pb-blist-trigger.js
src/main/resources/scripts/jenkins/pb-pr-trigger.js

The only deprecated library we are still using is aui. aui has been split up into several different packages. 
The modals we use in manual builds now require aui/dialog instead. I could not find an AMD valid i18n package so I removed it for now. I also could not find where the contextPath helper function moved to. I think atlassian may have removed it entirely so I'm stripping it out of the window.location.href instead.
I've tested that regular automated builds trigger normally, as do manual builds on all pages. However, I think the pop-up for user credentials may be broken. I'll see if I can fix it but I think we can probably leave it broken for now if need be.

Bitbucket Server 6.0.0 Compatibility

---

parameterized-client/src/hook/view.js
pom.xml
src/main/resources/scripts/jenkins/feature/build-dialog.js
src/main/resources/scripts/jenkins/pb-pr-trigger.js

The 4.0.0 version introduced javascript code that assumed repo slugs would only contain alphanumeric characters. This is not true for new versions of bitbucket server and caused the repo hook settings to fail to load (see #183).
This PR updates the regular expressions used to parse repository slugs to include all characters allowed in repository names.

Update regex to include repo-specific special characters

---

parameterized-client/src/hook/view.js
pom.xml
src/main/resources/scripts/jenkins/feature/build-dialog.js

Relates to the recent comment in #183. 
According to Bitbucket, "Repository names are limited to 128 characters. They must start with a letter or number and may contain spaces, hyphens, underscores and periods" Therefore, we should only have to add periods to the square brackets. However, it is possible Bitbucket could change this so might as well just allow any characters.
I've only tested that this works with the view.js file but I see no reason it would be problematic in the build-dialog.

Expect any character in project and repo names

---

.travis.yml
src/main/resources/atlassian-plugin.xml

A recent AMPS update broke rest doc generation for projects with rest components (see [this atlassian issue](https://community.developer.atlassian.com/t/error-when-trying-to-build-my-jira-projects-failed-to-execute-goal-com-atlassian-maven-plugins8-0-0-generate-rest-docs/27070)). The current workaround is to remove the package attribute of the rest component in the atlassian-plugin.xml file. This PR resolves #201.

Rest docs workaround

---

README.md
parameterized-client/src/hook/job.js
src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/BitbucketVariables.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/item/BitbucketVariablesTest.java

it is now possible to trigger jenkins also on pull requests which were
created from a fork.
two new variables were introduced for this:
$PRSOURCEPROJECT:    the PROJECT where the source repository resides
$PRSOURCEREPOSITORY: the REPOSITORY where the source branch resides
the existing $PROJECT and $REPOSITORY will continue to point to the
destination, even though it might have been more logical to flip the two
(instead introducing $PRTARGET[PROJECT|REPOSITORY]) so that all jobs can
just use $PROJECT and $REPOSITORY and not care whether it is a pull
request or not. however, this would be a breaking change for existing
consumers which use $PROJECT and $REPOSITORY in a fork-setup on pull
requests (though they currently can't actually build the project since
they lack the necessary …

add proper support for forks

---

parameterized-client/src/common/aui.js
parameterized-client/src/common/rest.js
parameterized-client/src/jenkins_settings/server.js

This PR fixes a bad null check that prevented jenkins settings from being saved if no settings already existed. It also adds some tweaks to the clear settings button to be more responsive.

Fix admin settings

---

pom.xml
src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/ServerService.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/JenkinsTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/item/JobTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/GlobalResourceTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/ProjectResourceTest.java

The current version of the plugin does not support special characters hardcoded in job build parameters as noted in #212. This is because only the values of the bitbucket variables are encoded properly.
This PR changes the building of the url to use `org.apache.http.client.utils.URIBuilder` instead of `javax.ws.rs.core.UriBuilder`. The new URIBuilder automatically encodes all query params for us where the old UriBuilder would inconsistently encode some values but not others. I also added additional validation on server base urls to ensure some of the new behaviors of URIBuilder do not cause build errors.

Allow special characters in build parameters

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/JenkinsTest.java

Solves #221. Since the new UriBuilder overrides the path segments provided, we need to start with a list of path segments from the base url.

Use url context from base url

---

pom.xml
src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java

I'm getting a lot of issues running new versions of the plugin because of Bitbucket sometimes complaining about "setPathSegments" method not found. It seems like there's some sort of race condition happening that causes Bitbucket to sometimes use an old version of httpclient? Either way, reverting to an earlier version seems to make things more consistent.

Downgrade http-client to fix runtime errors

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/GlobalResource.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/ProjectResource.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/ServerService.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/GlobalResourceTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/ProjectResourceTest.java

Currently, jenkins settings validation happens without the currently set token. I figured that it would make more sense that way because you could test what was currently on the page. However, this does cause a divergence in behavior between what happens on save and test. Since the current ui around the token is a little confusing, it just causes confusion about what is going on under the hood (see #219).
This PR aims to create validation like saving. That should at least resolve some of the confusion around token handling. The UI still needs to be updated to be clearer though.

[#219] Test Jenkins settings with token

---

README.md
parameterized-client/src/hook/job.js
parameterized-client/src/hook/state-reducers.js
src/main/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHook.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PushHandler.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsService.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/ParameterizedBuildHookTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/PushHandlerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/eventHandlers/RefHandlerTest.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsServiceTest.java

#134 
Added to new fields `Ignore Committers` and `Ignore Commits With String` for `PUSH EVENT` trigger.
**Ignore Committers** -- This option can be used to configure the list of users whose commit will not run the automatic CI build.
**Ignore Commits With String** -- Configure string and if it is found in the any commit message, that commit will be ignored and no build will be triggered.
tested the both options and made changes in test cases accordingly.

add Ignore Committers, Ignore Commits With String features

---

parameterized-client/src/common/rest.js
parameterized-client/src/jenkins_settings/server.js
src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/ServerService.java

Forward slashes in the alias can cause the server definition to become uneditable as brought up in #241. This is because it messes with the rest url in future calls. To prevent this from happening, we should not allow forward slashes to be saved in the first place.
This PR adds checks in both the client and server. The client side validation allows for quicker and easier feedback about the issue while the server side validation prevents rest requests outside of the UI from causing issues.

Do not allow forward slash in server alias

---

src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsService.java

Upgrading with jobs defined will cause null pointer exceptions. Need to check if these new keys exist before calling toString.

Fix unreleased bug on master

---

pom.xml
src/main/java/com/kylenicholls/stash/parameterizedbuilds/item/Job.java

When a branch contains an unencoded char such as `/` the PR based triggers do not trigger the job properly. This fix encodes the branch name before adding it to the build url.

Properly encode multibranch pipeline job names

---

pom.xml
src/main/java/com/kylenicholls/stash/parameterizedbuilds/helper/SettingsService.java
src/main/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResource.java
src/test/java/com/kylenicholls/stash/parameterizedbuilds/rest/BuildResourceTest.java

Because of the Bitbucket 7 updates around registering extensions, we need to expect that settings may not exist for a repo. This PR adds better null checks and response codes for calls made from repos that do not use the plugin.

Fix issues with no settings present

---

src/main/resources/scripts/jenkins/pb-pr-trigger.js

Adopted the regex used to determine the BitBucket server hostname in order to allow any character in the project's name.
Fixes #289.

Fix regex in PR trigger (allow any character in project names)

---

parameterized-client/src/hook/view.js
src/main/resources/atlassian-plugin.xml

For #296
When the hook allows it, repositories will default to inheriting the project's settings.
atlassian-plugin.xml add scopes to allow the hook to be configured at the project level.
view.js handle the view happening on either the repository or the project level.

Allow project-level settings.

---

src/main/resources/scripts/jenkins/feature/build-dialog.soy

Fixes Invalid <label for=> target and incorrect use of value variable, which is a real boolean, not a string.

Fixes #306: boolean fields incorrect label and incorrect default values

---

parameterized-client/src/common/rest.js

Since alias isn't really used, give a default if it is missing.

[#328] Provide dummy alias if missing
